---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maju5496/finanssia.com
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -av --delete --exclude .git/ --exclude .cpanel.yml ./ $DEPLOYPATH/
    - /bin/chmod 755 /home/maju5496/finanssia.com
    - /usr/bin/find /home/maju5496/finanssia.com -type d -exec chmod 755 {} \;
    - /usr/bin/find /home/maju5496/finanssia.com -type f -exec chmod 644 {} \;