---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maju5496/preview.finanssia.com.maju5496.odns.fr
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -av --delete --exclude .git/ --exclude .cpanel.yml ./ $DEPLOYPATH/